name: ChestShop
# Bump version to reflect removal of LP branding
version: '1.0.4'
main: org.luigilp.lPChestShop.LPChestShop
api-version: '1.20'
softdepend: [Vault]

commands:
  chestshop:
    # Updated the base command to remove the LP prefix.  Original command names
    # remain as aliases to ensure backward compatibility.
    description: Main command for ChestShop.
    usage: /chestshop <create|reload|remove|info|help>
    aliases: [lpcs, lpchestshop]

permissions:
  lpchestshop.create:
    description: Allows creating shops.
    default: true
  lpchestshop.reload:
    description: Allows reloading config/messages.
    default: op
  lpchestshop.remove.own:
    description: Allows removing your own shop (via breaking sign twice with axe).
    default: true
  lpchestshop.remove.any:
    description: Allows removing any shop.
    default: op
  lpchestshop.bypass:
    description: Bypass restrictions (open any shop chest, deposit anything).
    default: op
